### ISSUE TITLE
Create Post using Markdown Language

### ISSUE THREAD

**Issue by tasnimzotder** [tasnimzotder/hacktoberfest-2021-little-steps#8]
Create a simple post on Climate-Change and World Hunger using markdown language. The process the documented here 👉 
 https://github.com/tasnimzotder/hacktoberfest-2021-little-steps#readme

The format is like 👇

```markdown
---
username: <YOUR_USERNAME>
title: <TITLE>
date: <MONTH DATE, YEAR>
cover_img: '<YOUR_IMAGE_URL>'
excerpt: <EXCERPT>
---

# <TITLE>

<CONTENT>
```

By opening a PR, make an awareness in this planet.

**Comment by pritambera2000** [comment]
I'm a Beginner , please assign me in this project.

**Comment by tasnimzotder** [comment]
Sure @pritambera2000 You just open a PR according to the guideline given in the `README.md` file.

**Comment by tasnimzotder** [comment]
Markdown language reference 📝 👉 https://guides.github.com/features/mastering-markdown/
